# Configuration for https://github.com/wei/pull
version: "1"
rules:
  - base: upstream
    upstream: clearlydefined:master
    mergeMethod: hardreset
    mergeUnstable: false
  - base: upstream
    upstream: main
    mergeMethod: rebase
    assignees:
      - howbag
    reviewers:
      - howbag
    conflictReviewers:
      - howbag
label: "kind/sync"
conflictLabel: "state/conflict"
