name: Sync Fork

on:
  schedule:
    - cron: '0 * * * *' # every hour
  workflow_dispatch: # on button click

jobs:
  reset-upstream:
    runs-on: ubuntu-latest
    name: Reset our upstream branch to the upstream repo
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: clearlydefined/curated-data
          token: ${{ secrets.SYNC_BOT_TOKEN }}
          fetch-depth: 0
          fetch-tags: true
      - name: Configure git
        shell: bash
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "noreply@konflux-ci.dev"
          git remote add downstream https://synchrontron:${{ secrets.SYNC_BOT_TOKEN }}@github.com/konflux-ci/curated-data.git
      - name: Fetch and merge
        id: fetch-merge
        shell: bash
        run: |
          git checkout master
          git push --tags downstream master:upstream --force
  rebase-downstream:
    needs: [reset-upstream]
    runs-on: ubuntu-latest
    name: Rebase our downstream branch on upstream branch
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNC_BOT_TOKEN }}
          fetch-depth: 0
      - name: Configure git
        shell: bash
        run: |
          git config --global user.name "Sync Bot"
          git config --global user.email "noreply@konflux-ci.dev"
      - name: Rebase and push
        id: fetch-merge
        shell: bash
        run: |
          git checkout downstream
          git rebase upstream
          git push origin downstream --force
